name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      kafka:
        image: wurstmeister/kafka:2.13-2.7.0
        ports:
          - 9092:9092
        env:
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        options: >-
          --network-alias kafka

      zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        ports:
          - 2181:2181

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t libnjkafka-build .

    - name: Run Ruby C extension demo
      run: |
        docker run --network host --name libnjkafka-container libnjkafka-build make ruby_demo
