name: docker-image-cache/restore
description: Cache docker images as tar files

inputs:
  tag:
    description: Docker image tag
    required: true
  key:
    description: Cache key, see actions/cache
    required: false
  path:
    description: Cache path, see actions/cache
    required: false
  platform:
    description: Docker build platform
    required: false
    default: linux/amd64
  file:
    description: Dockerfile path
    required: false
    default: Dockerfile

outputs:
  cache-hit:
    description: If image was present in cache, see actions/cache.
    value: ${{ steps.restore.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Set values
      id: set-values
      shell: bash
      run: |
        default_key="${{ inputs.tag }}-${{ inputs.platform }}-${{ hashFiles(inputs.file) }}"
        echo "default_key=$default_key"
        input_key="${{ inputs.key }}"
        key=${input_key:-$default_key}

        default_path="/tmp/$key.tar"
        echo "default_path=$default_path"
        input_path="${{ inputs.path }}"
        path=${input_path:-$default_path}

        echo "key=$key"
        echo "path=$path"
        echo "key=$key" >> $GITHUB_OUTPUT
        echo "path=$path" >> $GITHUB_OUTPUT

    - name: Restore image
      id: restore
      uses: actions/cache/restore@v5
      with:
        path: ${{ steps.set-values.outputs.path }}
        key: ${{ steps.set-values.outputs.key }}
        fail-on-cache-miss: true

    - name: Load Docker image
      shell: bash
      run: docker load --input ${{ steps.set-values.outputs.path }}
