name: Build and test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: libnjkafka:${{ github.ref_name }}-${{ github.sha }}
      KAFKA_TOPIC: kafka-build-topic
      KAFKA_BROKERS: localhost:9092

    steps:
    - uses: actions/checkout@v4

    - name: Pull the docker-compose stack
      run: docker compose pull --quiet

    - name: Bring up docker-compose stack
      run: docker compose up --detach

    - uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: ${{ env.DOCKER_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platform: linux/amd64
        build-args: |
          ARCHITECTURE=x64
          GRAALVM_SHA256=46ec9582ebe114f93470403f2cc123238ac0c7982129c358af7d8e1de52dd663

    - name: Ensure the broker is up
      run: docker compose exec --no-TTY broker sh -c 'cub kafka-ready -b localhost:9092 1 30'

    - name: Build the library
      run: |
        docker run --network=host \
          --platform=linux/amd64 \
          --volume ${{ github.workspace }}:/libnjkafka \
          --env KAFKA_BROKERS=${{ env.KAFKA_BROKERS }} \
          --env KAFKA_TOPIC=${{ env.KAFKA_TOPIC }} \
          ${{ env.DOCKER_TAG }} \
          make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/

  c-tests:
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_TAG: libnjkafka:${{ github.ref_name }}-${{ github.sha }}
      KAFKA_TOPIC: kafka-build-topic
      KAFKA_BROKERS: localhost:9092

    steps:
    - name: Bring up docker-compose stack
      run: docker compose up --detach

    - name: Ensure the broker is up
      run: docker compose exec --no-TTY broker sh -c 'cub kafka-ready -b localhost:9092 1 30'

    - name: Run the C test program
      run: |
        docker run --network=host \
          --platform=linux/amd64 \
          --volume ${{ github.workspace }}:/libnjkafka \
          --env KAFKA_BROKERS=${{ env.KAFKA_BROKERS }} \
          --env KAFKA_TOPIC=${{ env.KAFKA_TOPIC }} \
          ${{ env.DOCKER_TAG }} \
          make c-demo

  build-ruby:
    runs-on: ubuntu-latest
    needs: build
    env:
      DOCKER_TAG: libnjkafka:${{ github.ref_name }}-${{ github.sha }}
      KAFKA_TOPIC: kafka-build-topic
      KAFKA_BROKERS: localhost:9092

    steps:
    - name: Bring up docker-compose stack
      run: docker compose up --detach

    - uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile.ruby
        load: true
        tags: ${{ env.DOCKER_TAG }}-ruby
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Ensure the broker is up
      run: docker compose exec --no-TTY broker sh -c 'cub kafka-ready -b localhost:9092 1 30'

    - name: Compile the Ruby C extension and run the demo program
      run: |
        docker run --network=host \
          --platform=linux/amd64 \
          --volume ${{ github.workspace }}:/libnjkafka \
          --env KAFKA_BROKERS=${{ env.KAFKA_BROKERS }} \
          --env KAFKA_TOPIC=${{ env.KAFKA_TOPIC }} \
          ${{ env.DOCKER_TAG }}-ruby \
          make ruby-demo
