name: Build and test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ "main" ]

env:
  COMPILER_IMAGE_PATH: /tmp/compiler-image.tar
  BROKER_IMAGE_PATH: /tmp/broker-images.tar

jobs:

  compiler-docker-image:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: libnjkafka:gha
    steps:
    - uses: actions/checkout@v6

    - name: Check Docker image cache
      uses: actions/cache@v5
      id: compiler-image
      with:
        path: ${{ env.COMPILER_IMAGE_PATH }}
        key: compiler-image-${{ hashFiles('Dockerfile') }}
        lookup-only: true

    - name: Build Docker image
      if: steps.compiler-image.outputs.cache-hit != 'true'
      run: |
        docker build \
          --build-arg ARCHITECTURE=x64 \
          --tag ${{ env.DOCKER_TAG }} \
          .
        docker save ${{ env.DOCKER_TAG }} --output ${{ env.COMPILER_IMAGE_PATH }}

    - name: Save Docker image
      if: steps.compiler-image.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ${{ env.COMPILER_IMAGE_PATH }}
        key: compiler-image-${{ hashFiles('Dockerfile') }}

  broker-docker-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Check Docker image cache
      uses: actions/cache@v5
      id: broker-images
      with:
        path: ${{ env.BROKER_IMAGE_PATH }}
        key: broker-images-${{ hashFiles('docker-compose.yml') }}
        lookup-only: true

    - name: Pull and save images
      if: steps.broker-images.outputs.cache-hit != 'true'
      run: |
        docker compose pull --quiet
        docker save $(docker compose config --images) --output ${{ env.BROKER_IMAGE_PATH }}

    - name: Save images to cache
      if: steps.broker-images.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ${{ env.BROKER_IMAGE_PATH }}
        key: broker-images-${{ hashFiles('docker-compose.yml') }}

  native_binaries:
    runs-on: ubuntu-latest
    needs:
      - compiler-docker-image
      - broker-docker-images
    env:
      DOCKER_TAG: libnjkafka:gha
      KAFKA_TOPIC: kafka-build-topic
      KAFKA_BROKERS: localhost:9092

    steps:
    - uses: actions/checkout@v6

    - name: Show the checked out files
      run: |
        ls -l
        ls -l csrc
        ls -l include

    - name: Reset mtimes
      run: |
        apt-get install git-restore-mtime
        git-restore-mtime --verbose

    - name: Show the checked out files again
      run: |
        ls -l
        ls -l csrc
        ls -l include

    - name: Restore binary cache
      uses: actions/cache@v5
      id: native-binaries-cache
      with:
        key: native-binaries-${{ hashFiles('csrc/*.c', 'include/*.h', 'src/**/*.java') }}
        path: build/

    - name: Restore broker images from cache
      uses: actions/cache/restore@v5
      with:
        path: ${{ env.BROKER_IMAGE_PATH }}
        key: broker-images-${{ hashFiles('docker-compose.yml') }}
        fail-on-cache-miss: true

    - name: Show the restored files
      run: |
          ls -l build/
          ls -l build/Linux*

    - name: Start broker
      run: |
        docker load --input ${{ env.BROKER_IMAGE_PATH }}
        docker compose up --detach

    - name: Restore Docker image from cache
      uses: actions/cache/restore@v5
      with:
        path: ${{ env.COMPILER_IMAGE_PATH }}
        key: compiler-image-${{ hashFiles('Dockerfile') }}
        fail-on-cache-miss: true

    - name: Load Docker image
      run: docker load --input ${{ env.COMPILER_IMAGE_PATH }}

    - name: Ensure the broker is up
      run: docker compose exec --no-TTY broker sh -c 'cub kafka-ready -b localhost:9092 1 30'

    - name: Build the library
      if: steps.native-binaries-cache.outputs.cache-hit != 'true'
      run: |
        docker run --network=host \
          --platform=linux/amd64 \
          --volume ${{ github.workspace }}:/libnjkafka \
          --env KAFKA_BROKERS=${{ env.KAFKA_BROKERS }} \
          --env KAFKA_TOPIC=${{ env.KAFKA_TOPIC }} \
          ${{ env.DOCKER_TAG }} \
          make

    - name: Run the C test program
      run: |
        docker run --network=host \
          --platform=linux/amd64 \
          --volume ${{ github.workspace }}:/libnjkafka \
          --env KAFKA_BROKERS=${{ env.KAFKA_BROKERS }} \
          --env KAFKA_TOPIC=${{ env.KAFKA_TOPIC }} \
          ${{ env.DOCKER_TAG }} \
          make c-demo

    - name: Upload build artifacts
      uses: actions/upload-artifact@v6
      with:
        name: native_binaries
        path: build/

    - name: Save binaries and headers to cache
      if: steps.native-binaries-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: build/
        key: native-binaries-${{ hashFiles('csrc/*.c', 'include/*.h', 'src/**/*.java') }}

  ruby-docker-image:
      runs-on: ubuntu-latest
      needs:
        - native_binaries
        - broker-docker-images
      env:
        DOCKER_TAG: libnjkafka-ruby:gha
        RUBY_IMAGE_PATH: /tmp/ruby-image.tar

      steps:
      - uses: actions/checkout@v6

      - uses: actions/download-artifact@v8
        with:
          name: native_binaries
          path: ./build

      - name: Show artifacts
        run: ls -l build

      - name: Build Docker image
        run: |
          docker build \
            --tag ${{ env.DOCKER_TAG }} \
            --file Dockerfile.ruby \
            .

      - name: Compile the Ruby C extension and run the Ruby tests
        run: |
          docker run --network=host \
            --volume ${{ github.workspace }}:/libnjkafka \
            --env KAFKA_BROKERS=${{ env.KAFKA_BROKERS }} \
            --env KAFKA_TOPIC=${{ env.KAFKA_TOPIC }} \
            ${{ env.DOCKER_TAG }} \
            make ruby-c-ext
